baseURL = "https://sdhanshu.github.io"
title = "Sudhanshu Choudhary"
googleAnalytics = "UA-154792779-1"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    portrait = "PHOTO.jpg"
    author = "Sudhanshu Choudhary"
    description = "Student | Programmer"
    bio = """
    <p> I am a 13 years old Programmer. I am an 8th grade student at Kendriya Vidhyalya. I live in Delhi, India. Preparing for the upcoming exams.</p>
    <br />
    <p>I love to code and solve problems. I have worked with programming languages like Python and C++. Experienced working with Google Actions and currently participating in Google Code-In (GCI).</p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[[menu.icon]]
    url = "mailto:sudhanshuchoudhary2005@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sdhanshu"
    name = "github"
    weight = 1

