baseURL = "https://sdhanshu.github.io"
title = "Sudhanshu Choudhary"
googleAnalytics = "UA-154792779-1"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    portrait = "photo.jpg"
    author = "Sudhanshu Choudhary"
    description = "Student | Programmer"
    bio = """
    <p> I am a 14 years old Programmer . I am a 9th grade student at Kendriya Vidhyalaya. I live in Delhi, India.</p>
    <br />
    <p> I enjoy Programming and Problem Solving. I have worked with programming languages like Python and C++. Experienced working with Google Actions and in Hacktoberfest. Currently Learning a Python Library called Manim.</p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.main]]
    identifier = "zone"
    name = "Zone"
    url = "/zone/"
    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[[menu.icon]]
    url = "mailto:sudhanshuchoudhary2005@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sdhanshu"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://gitter.im/ricksanc"
    name = "comments"
    weight = 4

[[menu.icon]]
    url = "https://www.linkedin.com/in/sudhanshu-choudhary-583a1519a/"
    name = "linkedin"
    weight = 3

