baseURL = "https://example.com"
title = "Sudhanshu Choudhary"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    author = "Sudhanshu Choudhary"
    description = "Student | Programmer"
    bio = """
    <p> I am a 13 years old boy. I am a grade 8 student at Kendriya Vidhyalya. </p>
    <br />
    <p>I love to code and solve problems.</p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[[menu.icon]]
    url = "mailto:sudhanshuchoudhary2005@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ricksanc/"
    name = "github"
    weight = 1

