baseURL = "https://sdhanshu.github.io"
title = "Sudhanshu Choudhary"
googleAnalytics = "UA-154792779-1"
theme = "erblog"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[params]
    portrait = "PHOTO.jpg"
    author = "Sudhanshu Choudhary"
    description = "Student | Programmer"
    bio = """
    <p> I am a Programmer who is 13 years old. I am an 8th grade student at Kendriya Vidhyalya. I live in India, Delhi. Trying to prepare for the upcoming examinations.</p>
    <br />
    <p> I enjoy Programming and Problem Solving. I have worked with programming languages like Python and C++. Experienced working with Google Actions and participating in Google Code-In (GCI) at the moment.</p>
    """
    copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[[menu.footer]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
category = "categories"
tag = "tags"

[[menu.icon]]
    url = "mailto:sudhanshuchoudhary2005@gmail.com"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://github.com/sdhanshu"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://gitter.im/ricksanc"
    name = "comments"
    weight = 3
    